import createDOMPurify, { type DOMPurify } from 'dompurify'
import { nanoid } from 'nanoid'

const githubDisallowedTags = [
  'audio',
  'base',
  'button',
  'datalist',
  'dialog',
  'embed',
  'fieldset',
  'form',
  'iframe',
  'input',
  'legend',
  'link',
  'meta',
  'noembed',
  'noframes',
  'object',
  'optgroup',
  'option',
  'output',
  'plaintext',
  'script',
  'select',
  'source',
  'style',
  'textarea',
  'title',
  'track',
  'video',
  'xmp',
]

// Mirrors the safe structural subset used by GitHub's open-source HTML
// pipeline while excluding resource-loading picture/source elements.
const githubMarkdownTags = [
  'a',
  'abbr',
  'b',
  'bdo',
  'blockquote',
  'br',
  'caption',
  'cite',
  'code',
  'dd',
  'del',
  'details',
  'dfn',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'ins',
  'kbd',
  'li',
  'mark',
  'ol',
  'p',
  'pre',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'small',
  'span',
  'strike',
  'strong',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'time',
  'tr',
  'tt',
  'ul',
  'var',
  'wbr',
]

const githubMarkdownAttributes = [
  'abbr',
  'align',
  'alt',
  'border',
  'char',
  'charoff',
  'cite',
  'clear',
  'colspan',
  'compact',
  'datetime',
  'dir',
  'frame',
  'headers',
  'height',
  'href',
  'hreflang',
  'hspace',
  'lang',
  'loading',
  'longdesc',
  'name',
  'noshade',
  'nowrap',
  'open',
  'rel',
  'rev',
  'role',
  'rowspan',
  'rules',
  'scope',
  'span',
  'src',
  'start',
  'summary',
  'tabindex',
  'title',
  'type',
  'valign',
  'width',
]

const inertImageSource =
  'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='

let markdownSanitizer: DOMPurify | undefined

function getMarkdownSanitizer(): DOMPurify | undefined {
  if (markdownSanitizer) {
    return markdownSanitizer
  }
  if (typeof window === 'undefined') {
    return undefined
  }

  // Mermaid also uses DOMPurify and installs global hooks. A private instance
  // keeps user HTML policy deterministic regardless of render order.
  markdownSanitizer = createDOMPurify(window)
  return markdownSanitizer
}

/**
 * Keep user-authored HTML close to GitHub's safe Markdown subset.
 *
 * Rich blocks generated by Mermaid and MathJax are added after this pass, so
 * their SVG markup isn't stripped by the HTML-only profile.
 */
export interface SanitizeMarkdownHtmlOptions {
  preserveImageSources?: boolean
}

export function createInertPreviewImageAttributes(source: string) {
  return {
    'data-mf-preview-image-id': nanoid(),
    'data-mf-preview-image-source': encodeURIComponent(source),
    src: inertImageSource,
  }
}

function sanitizeUserHtml(html: string): string {
  return (
    getMarkdownSanitizer()?.sanitize(html, {
      ADD_ATTR: [
        'data-mf-preview-image-id',
        'data-mf-preview-image-source',
        'data-mf-preview-trusted',
        'data-mf-preview-trusted-node',
      ],
      ALLOWED_ATTR: githubMarkdownAttributes,
      ALLOWED_TAGS: githubMarkdownTags,
      ALLOW_ARIA_ATTR: true,
      ALLOW_DATA_ATTR: false,
      FORBID_ATTR: [
        'autofocus',
        'class',
        'contenteditable',
        'id',
        'popover',
        'popovertarget',
        'srcdoc',
        'srcset',
        'style',
      ],
      FORBID_TAGS: githubDisallowedTags,
      SANITIZE_NAMED_PROPS: true,
    }) ?? ''
  )
}

export function sanitizeMarkdownHtml(
  html: string,
  options: SanitizeMarkdownHtmlOptions = {},
): string {
  if (!options.preserveImageSources || typeof document === 'undefined') {
    return sanitizeUserHtml(html)
  }

  const template = document.createElement('template')
  template.innerHTML = html
  template.content.querySelectorAll<HTMLImageElement>('img[src]').forEach((image) => {
    if (
      image.getAttribute('src') === inertImageSource &&
      image.dataset.mfPreviewImageId &&
      image.dataset.mfPreviewImageSource
    ) {
      return
    }

    const source = image.getAttribute('src')
    if (!source) {
      return
    }

    Object.entries(createInertPreviewImageAttributes(source)).forEach(([name, value]) => {
      image.setAttribute(name, value)
    })
  })

  return sanitizeUserHtml(template.innerHTML)
}

export function getPreviewImageSource(image: HTMLImageElement): string | null {
  if (
    image.getAttribute('src') === inertImageSource &&
    image.dataset.mfPreviewImageId &&
    image.dataset.mfPreviewImageSource
  ) {
    try {
      return decodeURIComponent(image.dataset.mfPreviewImageSource)
    } catch {
      return null
    }
  }

  return image.getAttribute('src')
}

export function clearPreviewImageSource(image: HTMLImageElement): void {
  delete image.dataset.mfPreviewImageId
  delete image.dataset.mfPreviewImageSource
}

export function sanitizeImageSource(source: string): string | null {
  return getMarkdownSanitizer()?.isValidAttribute('img', 'src', source) ? source : null
}

export function sanitizeGeneratedHtml(html: string): string {
  return (
    getMarkdownSanitizer()?.sanitize(html, {
      ALLOW_DATA_ATTR: true,
      FORBID_TAGS: githubDisallowedTags,
      SANITIZE_NAMED_PROPS: true,
      USE_PROFILES: { html: true, svg: true, svgFilters: true },
    }) ?? ''
  )
}
