export { default as useGlobalCacheData } from './useCacheData'
export { default as useGlobalSettingData } from './useSettingData'
export { default as useGlobalTheme } from './useTheme'
export { default as useGlobalKeyboard } from './useKeyboard'
export { default as useGlobalOSInfo } from './useOSInfo'
