import { markflowyLightTheme, webSpecificTokens } from '@markflowy/theme'

/** Shared visual language for Web. Desktop keeps its own theme. */
export const websiteTheme = {
  ...webSpecificTokens,
  ...markflowyLightTheme,
  primaryBg: '#ffffff',
  primaryText: '#0a2540',
  secondaryBg: '#f6f9fc',
  secondaryText: '#425466',
  secondaryFontColor: '#52657a',
  navBackground: 'rgba(255, 255, 255, 0.94)',
  footerBgColor: '#f6f9fc',
  sidebarBackground: '#ffffff',
  bgColor: '#ffffff',
  bgColorSecondary: '#f6f9fc',
  primaryFontColor: '#0a2540',
  unselectedFontColor: '#52657a',
  labelFontColor: '#52657a',
  borderColor: '#e3e9ef',
  accentColor: markflowyLightTheme.accentColor,
  accentColorFocused: markflowyLightTheme.accentColorFocused,
  borderColorFocused: markflowyLightTheme.borderColorFocused,
  webPaper: '#ffffff',
  webPaperWarm: '#f6f9fc',
  webPaperDark: '#edf2f7',
  webInk: '#0a2540',
  webInkSoft: '#425466',
  webInkMute: '#52657a',
  webInkFaint: '#65788c',
  webSeal: markflowyLightTheme.accentColor,
  webSealSoft: markflowyLightTheme.accentColor,
  webInkWash: '#8395ad',
  webLine: '#d5dfe9',
  webLineSoft: '#e5ebf1',
  webLineFaint: '#f0f3f7',
  webShadow: '0 24px 60px -24px rgba(10, 37, 64, 0.25)',
  webFontSans:
    "'Inter', -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Microsoft YaHei', sans-serif",
  webFontBody:
    "'Inter', -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Microsoft YaHei', sans-serif",
}

/** Application surfaces use the same palette with denser editor-specific tokens. */
export const applicationTheme = {
  ...websiteTheme,
  fontFamily: websiteTheme.webFontSans,
  disabledFontColor: websiteTheme.webInkFaint,
  hoverColor: '#eef4fc',
  titleBarBgColor: websiteTheme.webPaper,
  titleBarDefaultHoverColor: websiteTheme.webPaperWarm,
  editorTabBgColor: websiteTheme.webPaperWarm,
  editorTabActiveBgColor: websiteTheme.webPaper,
  editorToolbarBgColor: websiteTheme.webPaper,
  sideBarBgColor: websiteTheme.webPaperWarm,
  sideBarHeaderBgColor: websiteTheme.webPaperWarm,
  rightBarBgColor: websiteTheme.webPaper,
  rightBarHeaderBgColor: websiteTheme.webPaper,
  statusBarBgColor: websiteTheme.webPaper,
  fileTreeSelectedBgColor: '#e6effd',
  fileTreeIndentLineColor: websiteTheme.webLineSoft,
  tocbarProgressBgColor: websiteTheme.webPaperWarm,
  tocbarProgressActiveBgColor: websiteTheme.accentColor,
  buttonBgColor: websiteTheme.webPaper,
  contextMenuBgColor: websiteTheme.webPaper,
  contextMenuBgColorHover: '#eef4fc',
  contextMenuBgColorActive: '#e6effd',
  dialogBgColor: websiteTheme.webPaper,
  dialogBackdropColor: 'rgba(10, 37, 64, 0.24)',
  tipsBgColor: websiteTheme.webPaperWarm,
  tooltipBgColor: websiteTheme.webPaper,
  scrollbarTrackColor: 'transparent',
  scrollbarThumbColor: '#c2cedb',
  boxShadowColor: websiteTheme.webShadow,
  nodeSelectedColor: '#e6effd',
  blockquoteBorderColor: websiteTheme.accentColor,
  blockquoteFontColor: websiteTheme.webInkSoft,
  placeholderFontColor: websiteTheme.webInkFaint,
  preBgColor: websiteTheme.webPaperWarm,
  codeBgColor: websiteTheme.webPaperWarm,
  successColor: '#087f5b',
  dangerColor: '#c4324a',
  warnColor: '#9a6700',
  codemirrorFontFamily: websiteTheme.webFontMono,
}
