import { useTranslation } from '@/i18n'
export const themeLabelsEn = {
  installedOnly: 'Installed only',
  title: 'Themes',
  create: 'Create theme',
  import: 'Import JSON',
  export: 'Export JSON',
  edit: 'Edit',
  copy: 'Copy and edit',
  remove: 'Remove',
  apply: 'Apply',
  save: 'Save and apply',
  close: 'Close',
  undo: 'Undo',
  redo: 'Redo',
  search: 'Find a token…',
  modified: 'Modified only',
  reset: 'Reset',
  link: 'Link to token',
  value: 'Value',
  inspect: 'Inspect preview',
  snippets: 'Personal CSS snippets',
  addCss: 'Import CSS',
  createCss: 'New snippet',
  untitledCss: 'Untitled snippet',
  disableAll: 'Disable all',
  includeCss: 'Include personal CSS',
  up: 'Move up',
  down: 'Move down',
  name: 'Name',
  author: 'Author',
  variant: 'Variant',
  addLight: 'Add light variant',
  addDark: 'Add dark variant',
  advanced: 'Advanced JSON / CSS',
  css: 'Theme CSS',
  json: 'Theme JSON',
  applyJson: 'Update from JSON',
  revertJson: 'Discard JSON edits',
  pendingJson: 'Apply or discard the JSON edits to continue visual editing and export.',
  catalog: 'Community themes',
  install: 'Install',
  emptyCatalog: 'New community themes will appear here as JSON themes become available.',
  replace: 'This theme ID already exists. Replace it?',
  replaceAction: 'Replace',
  cancel: 'Cancel',
  saveCopy: 'Save a copy',
  draft: 'A local draft is available.',
  resume: 'Resume draft',
  discard: 'Discard draft',
  preview: 'Theme preview',
  loadError: 'Could not load the editor preview.',
  retry: 'Retry',
  linked: 'Linked',
  inherited: 'Default',
  customCss: 'Custom CSS may override the inspected token.',
  preferences:
    'Preview shows only the theme. Your chosen personal preferences also apply when using it.',
  personalTypography: 'Use personal fonts, size and line height',
  saved: 'Saved',
  error: 'Error',
  enabled: 'Enabled',
  editCss: 'Edit CSS',
  saveCss: 'Save snippet',
  noSnippets: 'No personal CSS snippets.',
  deleteConfirm: 'Remove this theme?',
  removeVariant: 'Remove variant',
  schema: 'Export JSON Schema',
}
export const themeLabelsZh: typeof themeLabelsEn = {
  installedOnly: '仅看已安装',
  title: '主题',
  create: '创建主题',
  import: '导入 JSON',
  export: '导出 JSON',
  edit: '编辑',
  copy: '复制并编辑',
  remove: '移除',
  apply: '应用',
  save: '保存并应用',
  close: '关闭',
  undo: '撤销',
  redo: '重做',
  search: '查找 token…',
  modified: '仅看修改项',
  reset: '恢复默认',
  link: '关联 token',
  value: '值',
  inspect: '检查预览元素',
  snippets: '个人 CSS 片段',
  addCss: '导入 CSS',
  createCss: '新建片段',
  untitledCss: '未命名片段',
  disableAll: '全部停用',
  includeCss: '包含个人 CSS',
  up: '上移',
  down: '下移',
  name: '名称',
  author: '作者',
  variant: '变体',
  addLight: '添加浅色变体',
  addDark: '添加深色变体',
  advanced: '高级 JSON / CSS',
  css: '主题 CSS',
  json: '主题 JSON',
  applyJson: '从 JSON 更新',
  revertJson: '丢弃 JSON 修改',
  pendingJson: '先应用或丢弃 JSON 修改，再继续可视化编辑和导出。',
  catalog: '社区主题',
  install: '安装',
  emptyCatalog: '转换为 JSON 格式的社区主题将在这里显示。',
  replace: '已有相同 ID 的主题，是否替换？',
  replaceAction: '替换',
  cancel: '取消',
  saveCopy: '另存副本',
  draft: '有可恢复的本地草稿。',
  resume: '恢复草稿',
  discard: '丢弃草稿',
  preview: '主题预览',
  loadError: '无法加载编辑器预览。',
  retry: '重试',
  linked: '已关联',
  inherited: '默认',
  customCss: '自定义 CSS 可能覆盖所检查的 token。',
  preferences: '此处仅预览主题，应用结果还会结合所选的个人偏好。',
  personalTypography: '使用个人字体、字号与行高',
  saved: '已保存',
  error: '错误',
  enabled: '启用',
  editCss: '编辑 CSS',
  saveCss: '保存片段',
  noSnippets: '暂无个人 CSS 片段。',
  deleteConfirm: '移除此主题？',
  removeVariant: '移除变体',
  schema: '导出 JSON Schema',
}
export function useThemeLabels() {
  const { i18n } = useTranslation()
  return i18n.language?.startsWith('zh') ? themeLabelsZh : themeLabelsEn
}
