import { useMemo } from 'react'
import { useTranslation } from '@/i18n'

export function useThemeLabels() {
  const { t } = useTranslation()
  return useMemo(
    () => ({
      installedOnly: t('settings.themeStore.controls.installedOnly'),
      title: t('settings.themeStore.controls.title'),
      create: t('settings.themeStore.controls.create'),
      import: t('settings.themeStore.controls.import'),
      export: t('settings.themeStore.controls.export'),
      edit: t('settings.themeStore.controls.edit'),
      copy: t('settings.themeStore.controls.copy'),
      remove: t('settings.themeStore.controls.remove'),
      apply: t('settings.themeStore.controls.apply'),
      save: t('settings.themeStore.controls.save'),
      close: t('settings.themeStore.controls.close'),
      undo: t('settings.themeStore.controls.undo'),
      redo: t('settings.themeStore.controls.redo'),
      search: t('settings.themeStore.controls.search'),
      modified: t('settings.themeStore.controls.modified'),
      reset: t('settings.themeStore.controls.reset'),
      link: t('settings.themeStore.controls.link'),
      value: t('settings.themeStore.controls.value'),
      inspect: t('settings.themeStore.controls.inspect'),
      snippets: t('settings.themeStore.controls.snippets'),
      addCss: t('settings.themeStore.controls.addCss'),
      createCss: t('settings.themeStore.controls.createCss'),
      untitledCss: t('settings.themeStore.controls.untitledCss'),
      disableAll: t('settings.themeStore.controls.disableAll'),
      includeCss: t('settings.themeStore.controls.includeCss'),
      up: t('settings.themeStore.controls.up'),
      down: t('settings.themeStore.controls.down'),
      name: t('settings.themeStore.controls.name'),
      author: t('settings.themeStore.controls.author'),
      variant: t('settings.themeStore.controls.variant'),
      addLight: t('settings.themeStore.controls.addLight'),
      addDark: t('settings.themeStore.controls.addDark'),
      advanced: t('settings.themeStore.controls.advanced'),
      options: t('settings.themeStore.controls.options'),
      previewOptions: t('settings.themeStore.controls.previewOptions'),
      closeAdvanced: t('settings.themeStore.controls.closeAdvanced'),
      noTokens: t('settings.themeStore.controls.noTokens'),
      css: t('settings.themeStore.controls.css'),
      json: t('settings.themeStore.controls.json'),
      applyJson: t('settings.themeStore.controls.applyJson'),
      revertJson: t('settings.themeStore.controls.revertJson'),
      pendingJson: t('settings.themeStore.controls.pendingJson'),
      catalog: t('settings.themeStore.controls.catalog'),
      install: t('settings.themeStore.controls.install'),
      emptyCatalog: t('settings.themeStore.controls.emptyCatalog'),
      replace: t('settings.themeStore.controls.replace'),
      replaceAction: t('settings.themeStore.controls.replaceAction'),
      cancel: t('settings.themeStore.controls.cancel'),
      saveCopy: t('settings.themeStore.controls.saveCopy'),
      draft: t('settings.themeStore.controls.draft'),
      resume: t('settings.themeStore.controls.resume'),
      discard: t('settings.themeStore.controls.discard'),
      preview: t('settings.themeStore.controls.preview'),
      loadError: t('settings.themeStore.controls.loadError'),
      retry: t('settings.themeStore.controls.retry'),
      linked: t('settings.themeStore.controls.linked'),
      inherited: t('settings.themeStore.controls.inherited'),
      customCss: t('settings.themeStore.controls.customCss'),
      preferences: t('settings.themeStore.controls.preferences'),
      personalTypography: t('settings.themeStore.controls.personalTypography'),
      saved: t('settings.themeStore.controls.saved'),
      error: t('settings.themeStore.controls.error'),
      enabled: t('settings.themeStore.controls.enabled'),
      editCss: t('settings.themeStore.controls.editCss'),
      saveCss: t('settings.themeStore.controls.saveCss'),
      noSnippets: t('settings.themeStore.controls.noSnippets'),
      deleteConfirm: t('settings.themeStore.controls.deleteConfirm'),
      removeVariant: t('settings.themeStore.controls.removeVariant'),
      schema: t('settings.themeStore.controls.schema'),
      light: t('settings.themeStore.controls.light'),
      dark: t('settings.themeStore.controls.dark'),
      catalogMismatch: t('settings.themeStore.controls.catalogMismatch'),
      previewNotes: t('settings.themeStore.controls.previewNotes'),
      previewIdeas: t('settings.themeStore.controls.previewIdeas'),
      previewWelcome: t('settings.themeStore.controls.previewWelcome'),
      previewSearch: t('settings.themeStore.controls.previewSearch'),
      previewSearchPlaceholder: t('settings.themeStore.controls.previewSearchPlaceholder'),
      previewNewNote: t('settings.themeStore.controls.previewNewNote'),
    }),
    [t],
  )
}
