export const nodeTypeIconMap: Record<string, string> = {
  'heading-1': 'ri-h-1',
  'heading-2': 'ri-h-2',
  'heading-3': 'ri-h-3',
  'heading-4': 'ri-h-4',
  'heading-5': 'ri-h-5',
  'heading-6': 'ri-h-6',
  paragraph: 'ri-paragraph',
  'list-bullet': 'ri-list-unordered',
  'list-ordered': 'ri-list-ordered',
  'list-task': 'ri-list-check-3',
  codeMirror: 'ri-code-box-line',
  table: 'ri-table-line',
  blockquote: 'ri-double-quotes-l',
  html_block: 'ri-html5-line',
  math_block: 'ri-formula',
  mermaid_node: 'ri-flow-chart',
  horizontalRule: 'ri-separator',
}
