name: Test CI

on: push

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Enable Corepack
        run: corepack enable

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Install rust target
        run: rustup target add x86_64-apple-darwin

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install verified Capricorn runtime
        run: yarn install:capricorn-runtime
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Build workspaces
        run: yarn build

      - name: Run Test
        run: yarn test
